honeybadger-io/honeybadger-ruby

- lib/honeybadger/monitor/trace.rb
In Ruby, `true` and `false` are global singleton instances. Freezing
them may lead to unexpected behaviour in some projects.
This code may have been introduced because of the common practice of
freezing other constants (such as arrays). I see no benefit in
freezing `true` or `false` themselves here.
Our particular problem in our projects comes from the special casing
of frozen variables with Rails[1]. This in combination of the Honeybadger code
causes some of our test to fail.
Although it would be good to fix this behaviour in Rails too, since
I believe the freezing here wasn’t intentional and many others will
be using honeybadger with Rails it would be good to fix it here too.
Also see a similar problem our team has had in the past with the sass gem [2].
[1] …
> Don’t freeze global instances of true and false

- vendor/capistrano-honeybadger/lib/capistrano/tasks/deploy.cap
This fixes an issue where the `honeybadger deploy` command fails during deployment when you are using the [capistrano-rvm](https://github.com/capistrano/rvm) gem. The failure message is: `bash: bundle: command not found`.
After some digging I discovered that the capistrano-rvm gem has a list of commands to which it will automatically appends the appropriate rvm commands, just like capistrano-bundler.
It's not mentioned in their documentation, but you can see it used in the load:defaults task [here](https://github.com/capistrano/rvm/blob/master/lib/capistrano/tasks/rvm.rake).
> Fix for capistrano-rvm compatibility

- vendor/capistrano-honeybadger/lib/capistrano/tasks/deploy.cap
Same issue as #112, but for [capistrano-rbenv](https://github.com/capistrano/rbenv).
> Fix for capistrano-rbenv compatibility

- vendor/capistrano-honeybadger/lib/honeybadger/capistrano/legacy.rb
The `honeybadger_user` option is mentioned in the documentation, but the legacy support for Capistrano v2 did not use it. This commit updates the v2 deploy task to fetch `honeybadger_user` the same way the v3 task uses it.
> Add support for honeybadger_user with Capistrano 2

- lib/honeybadger/agent/metrics_collection.rb
- lib/honeybadger/notice.rb
- lib/honeybadger/trace.rb
- spec/support/helpers.rb
While doing a bit of source diving I noticed a couple super minor readability improvements. Added guard clauses to reduce nesting in 3 methods. Also found one method with some extra leading whitespace.
I'm not sure if you even want pull requests of this nature, but figured I'd punt it over anyway.
Cheers!
> Tiny readability refactors for a few complex methods

- CHANGELOG.md
- lib/honeybadger/cli/main.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/config/env.rb
- lib/honeybadger/config/yaml.rb
- spec/unit/honeybadger/config/env_spec.rb
- spec/unit/honeybadger/config_spec.rb
Fix for #125.
* Adds explicit types for config options.
* Uses config types to cast values from ENV.
* Adds type documentation to `honeybadger config` command.
> Explicit config types

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
This references #107 and ignores the entire list of Rails' rescue
responses:
https://github.com/rails/rails/blob/116695b25890e2587923d4a237ce4107e3adb145/actionpack/lib/action_dispatch/middleware/exception_wrapper.rb#L8-L20
> Update default ignore list.

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/plugins/sidekiq.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
This is a port of #98 to 2.0. Sidekiq errors will not be sent to Honeybadger until they exceed `sidekiq.attempt_threshold` (default is `0`). Error notifications are always sent on the last job (when the retry limit is exceeded).
> Add sidekiq.attempt_threshold

- CHANGELOG.md
- lib/honeybadger/backend/debug.rb
- lib/honeybadger/cli/main.rb
- spec/features/deploy_spec.rb
- vendor/capistrano-honeybadger/lib/capistrano/tasks/deploy.cap
- vendor/capistrano-honeybadger/lib/honeybadger/capistrano/legacy.rb
This moves failure handling to Capistrano where we still ignore failures so that we don't kill the deployment when deploy notification times out.
> Fix deploy cmd exit code.

- CHANGELOG.md
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
The previous code blows up if it is passed an Exception object with
a :cause method that is not an Exception (or at least doesn't respond to
:message, :backtrace, etc).
I ran into this in the wild with the etcd-ruby gem:
https://github.com/ranjib/etcd-ruby/blob/master/lib/etcd/exceptions.rb
It was extremely painful to debug since the exception was intermittent and not reproducible in development, so at first I didn't think it had anything to do with Honeybadger.
> Don't choke on non-Exception causes

- lib/honeybadger/util/request_payload.rb
- lib/honeybadger/util/sanitizer.rb
- spec/unit/honeybadger/util/request_payload_spec.rb
- spec/unit/honeybadger/util/sanitizer_spec.rb
We noticed that honeybadger was not filtering values in HTTP_COOKIE that we had set in our `Rails.application.config.filter_parameters`. This led to them appearing in both the environment section and cookies section on Honeybadger.
This PR introduces a new `filter_cookies` to the `Util::Sanitizer` that is responsible for taking  a cookie string and sanitizing any sensitive values. We call this while building the request payload to ensure that sensitive values present in the HTTP_COOKIE are not sent to Honeybadger.
> Filter HTTP_COOKIE in request cgi_data

- lib/honeybadger/plugin.rb
File paths on Windows often start with a drive letter in the form of `\w:`. This solves the exception on Windows where the gem isn't able to load plugins via call stack detection.
> Fix CALLER_FILE regex

- vendor/capistrano-honeybadger/lib/capistrano/tasks/deploy.cap
Added honeybadger to the list of binaries recognized by [capistrano-chruby](https://github.com/capistrano/chruby). Hopefully this will be the last ruby manager that needs to be added. :smiley:
> Fixed compatibility with capistrano-chruby

- lib/honeybadger/util/sanitizer.rb
The url filtering mechanism can run into a string that has regex special characters which currently do not get escaped, which can wreck the replacement logic.
For example, a query parameter value that has a leading space gets URL-escaped to '+', which throws a Regex error because '+' is a special character that is not valid as the leading character in a regular expression.
> Fix url sanitization for strings with regex special characters.

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/init/rake.rb
- lib/honeybadger/notice.rb
- spec/features/rake_spec.rb
- spec/fixtures/Rakefile
I'm still pondering the implications of this change. Basically the idea is this:
- By default rake exceptions are enabled, but only when not attached to a terminal.
- Explicitly enabling rake exceptions means exceptions should be reported always.
- Explicitly disabling rake exceptions means exceptions should be reported never.
> Make TTY configurable for Rake reporting.

- README.md
Correct the documentation around `exception_filter` where it erroneously states that: 
"If your callback returns a falsey value, the exception won't be reported"
> Correct documentation on `exception_filter`

- CHANGELOG.md
- lib/honeybadger/notice.rb
- lib/honeybadger/util/sanitizer.rb
This fixes a bug where some gems (such as the dropbox gem) monkeypatch `#to_hash` on `Array`.
> Be stricter when sanitizing objects.

- README.md
The current URL (GitHub releases page) is not very useful, because the GitHub releases feature isn't used - it only shows the tags and not what changed. `CHANGELOG.md` is a much more useful link.
> Update Changelog URL in README

- lib/honeybadger/plugins/resque.rb
- spec/unit/honeybadger/plugins/resque_spec.rb
Call to retry_criteria_valid? was being made incorrectly, fixed and wrapped the whole thing in a begin/rescue/end block to prevent exceptions in that logic from being reported.
> Fix bug in resque-retry logic

- lib/honeybadger/plugins/resque.rb
- spec/unit/honeybadger/plugins/resque_spec.rb
Added specs covering resque-retry installed but not extended in worker class, cover exception thrown during retry_criteria_valid? call.
@joshuap This fixes an issue if the resque-retry gem was installed, a job not extending Resque::Plugins::Retry runs, and an exception is encountered, we tried to call retry_criteria_valid?, and it's not defined. Added specs over this, and the code added yesterday that wraps the whole thing in begin/rescue/end.
> Check that we respond to retry_criteria_valid?

- CHANGELOG.md
- lib/honeybadger/config.rb
- spec/unit/honeybadger/plugin_spec.rb
> Allow plugin names in config to be symbols or strings.

- CHANGELOG.md
- Gemfile.lock
- README.md
- circle.yml
- lib/honeybadger/agent.rb
- lib/honeybadger/config/defaults.rb
- spec/features/at_exit_spec.rb
- spec/fixtures/ruby_crash.rb
This causes exceptions in Rails runner code as well as any exception
which crashes a Ruby program to be automatically reported to
Honeybadger, as discussed in #150.
> Automatically report unhandled exceptions at exit.

- lib/honeybadger/backend/server.rb
We were performing some routine "lets change the time of the server and prod our app" in our integration environment and hit a bit of a blocker booting our app.
I'd expect the honeybadger gem to ignore the SSL errors resulting from the invalid SSL certificate, but we were seeing the following exception raised HB tried to ping the backend, crashing the app.
/opt/rubies/2.1.8/lib/ruby/2.1.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
Obviously this is suboptimal - this PR simply adds this exception class to the set of exceptions rescued and ignored.
> Rescue OpenSSL exceptions in backend calls

- lib/honeybadger/agent.rb
This should fix #186. I'm planning to do a larger threading overhaul to address our usage of `Thread.kill` in the future.
> Don't sleep in ensure.

- lib/honeybadger.rb
- spec/unit/honeybadger_spec.rb
There is a method for adding to the current context `Honeybadger.context(hash)` but I didn't see a public method for getting the current_context.  In the interest of being symmetrical I've added get_context.
My personal use case for this is that the context is not only a great thing to have for Honeybadger errors, but I wanted something like that to add context unobtrusively for other types of logs.  Loggly for example.  
Honeybadger already has vendor support for rack and Sidekiq middleware for clearing the context for each new request / job, and what's fair context for Honeybadger might as well be context for my Loggly logging as well, so why not just log what I want into Loggly merged on top of the current Honeybadger context: `Honeybadger.get_context`
> add method to get current context

- lib/honeybadger/config.rb
- lib/honeybadger/config/defaults.rb
- spec/unit/honeybadger/util/http_spec.rb
Under JRuby, `OpenSSL::X509::DEFAULT_CERT_FILE` returns a path to the java keystore, which is not in the PEM format [required by Net::HTTP#ca_file](http://www.rubydoc.info/stdlib/net/Net/HTTP#ca_file-instance_method). This effectively renders the `:'connection.system_ssl_cert_chain'` option a noop under JRuby.
To work around this issue, I've added the `:'connection.ssl_ca_bundle_path'` option.
> Allow custom ca bundle path for secure connections

- lib/honeybadger/plugins/shoryuken.rb
- spec/unit/honeybadger/plugins/shoryuken_spec.rb
This PR adds support for [Shoryuken](https://github.com/phstc/shoryuken), which is a Job queue manager, based on Sidekiq, but not completely compatible with it (hence the need of a new plugin).
Shoryuken supports doing batches of jobs at the same time. However, this will increase the complexity of reporting errors to Honeybadger, so right now it doesn't support them.
This plugin accepts the configuration option `shoryuken.attempt_threshold`, which is similar as Resque, and Sidekiq plugins.
I couldn't find documentation about coding style, or a contributing guide, but the link in your documentation page seems to be broken, or at least that section's gone (http://docs.honeybadger.io/lib/ruby.html#contributing)
> Add shoryuken integration

- lib/honeybadger/backend/server.rb
This fix prevents unicorn crash when ipv4 interface is absent.
During initialization process honeybadger does ping request and unicorn crashes due to `Errno::ENETUNREACH` exception isn't handled in `Server` backend
`Network is unreachable - connect(2) for "api.honeybadger.io" port 443`
> Fixes crash on unicorn start

- lib/honeybadger/trace.rb
Rails 5 adds a new attribute to the event payload for controller events.
This is the `headers` attribute, an instance of `ActionDispatch::Http::Headers`.
The honeybadger gem doesn't use the `headers` attribute. This commit
prevents it from being added to the payload sent to honeybager's API.
The reason we have to remove the `headers` attribute is because it
doesn't just contain HTTP headers. It contains a bunch of internal rails
objects, including an instance of the rails logger. The result of this
is that `headers.to_json` causes an IOError, as the JSON library
attempts to read from the logger's copy of STDOUT.
> remove headers from trace metadata for controller events

- lib/honeybadger/notice.rb
This PR only concerns the exceptoins.local_variables feature. When enabled:
Sometimes the local_variables returned by
`binding.eval('local_variables')` cannot be evaluated. In that case,
capture the NameError exception and move on.
To be a bit more specific, when I debug the code I see that, in one scenario in my Rails 4 app, `binding.eval('local_variables')` returns: `[:m, :args, :block, :r, :target]`. I'm not sure where the `m` variable comes from but trying to evaluate it blows up with a NameError exception.
> binding.eval('m')
> NameError (undefined local variable or method `m' for #<...>
So I've added exception handling to the local variable evals.
> Capture NameError exceptions when evaluating local_variables

- lib/honeybadger/plugins/delayed_job/plugin.rb
This causes Honeybadger to report nested exceptions in delayed jobs.
> Pass whole exception to notify_or_ignore

- .travis.yml
- CHANGELOG.md
- README.md
- lib/honeybadger/backend/base.rb
- lib/honeybadger/cli/deploy.rb
- lib/honeybadger/cli/exec.rb
- lib/honeybadger/cli/helpers.rb
- lib/honeybadger/cli/heroku.rb
- lib/honeybadger/cli/install.rb
- lib/honeybadger/cli/main.rb
- lib/honeybadger/cli/notify.rb
- lib/honeybadger/cli/test.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/yaml.rb
- lib/honeybadger/rack/user_feedback.rb
- lib/honeybadger/rack/user_informer.rb
- spec/features/deploy_spec.rb
- spec/features/notify_spec.rb
- spec/fixtures/rails/config/environment.rb
- spec/unit/honeybadger/config/yaml_spec.rb
- spec/unit/honeybadger/config_spec.rb
This in part addresses #217, and introduces some other semi-related changes/improvements. From the changelog:
- Exceptions encountered while loading/evaluating honeybadger.yml are now raised instead of logged.
- Friendlier backtraces for exceptions originating in honeybadger.yml.
- Rails environment is now loaded when running `honeybadger` cli from a Rails root. This fixes an issue where programmatic configuration from Rails was not loaded.
Also:
- Added test coverage for `honeybadger notify` CLI command.
- Updated development documentation.
- Better error messages for server/response-related issues.
> CLI Rails-improvements

- README.md
- lib/honeybadger/config.rb
- spec/unit/honeybadger/config_spec.rb
Noticed this in a pure Ruby app I was working on:
```
Bundler.require(:default) # this requires Honeybadger which inits the logger to STDOUT 
Honeybadger.configure do |config|
config.logger = Logger.new('/some/file')
end
```
The file specified would never actually get logged to; instead, logging would still show up in STDOUT.
I think [this](https://github.com/honeybadger-io/honeybadger-ruby/commit/ddbc18945842cc6a09b3b0ba58099641ace251b3#diff-af93e356bc211e1ecfdf85c19369f215R62) change meant to use `@logger` instead of `@logging`.
(I also fixed a typo in some other tests that I saw. LMK if you'd prefer I tear that commit out.)
> Logger isn't being overridden properly when configuring with Honeybadger.configure

- lib/honeybadger/cli/install.rb
- lib/honeybadger/cli/test.rb
- lib/honeybadger/plugins/rails.rb
- lib/honeybadger/version.rb
This prevents Rails and/or Rails-related integrations from being loaded if the gem happens to exist but the `honeybadger` command is not being run inside an actual Rails application.
> Require a Rails.application when loading Rails integrations

- CHANGELOG.md
- lib/honeybadger/plugins/rails.rb
*web-console* prepends `#render_exception` in
`ActionDispatch::DebugExceptions`, which causes a stack recursion error when we
alias method chain. Since we no longer support Ruby 1.9.3 we can switch to
prepend. There are a few other areas we use the old method which will be
changed in future PRs.
See also: https://github.com/rails/web-console/blob/b1fc057676204f069cab7dc86eb3b382320c25b6/lib/web_console/extensions.rb
> Fix conflict with the web-console gem

- CHANGELOG.md
- lib/honeybadger/plugins/resque.rb
- spec/unit/honeybadger/plugins/resque_spec.rb
This fixes a bug in the Resque plugin which prevented notifications from
being sent. The issue was that the Resque's callbacks were executed in
an unexpected order which caused the queue to be flushed before error
notification instead of after.
> Notify synchronously in Resque hook

- lib/honeybadger/backtrace.rb
- lib/honeybadger/cli/main.rb
- lib/honeybadger/rack/user_feedback.rb
- lib/honeybadger/util/stats.rb
- spec/unit/honeybadger/backtrace_spec.rb
Replaces deprecated method `exists?` with `exists`
- Ruby [prefers this](https://ruby-doc.org/core-2.2.0/File.html#method-c-exists-3F) as of 2.2.0
- Will get rid of lots of `File.exists? is a deprecated name` logspam warnings
> Replace File.exists? with File.exist?

- CHANGELOG.md
- lib/honeybadger/agent.rb
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
From the CHANGELOG:
> The exception cause may now be set using an optional `:cause` option when
> calling `Honeybadger.notify`. If not present, the exception's cause will be
> used, or the global `$!` exception if available.
> Allow overriding the cause.

- CHANGELOG.md
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
This adds support for adding context to exceptions when raising them:
```ruby
class CustomError < StandardError
attr_reader :honeybadger_context
def initialize(message, context = {})
@honeybadger_context = context
super(message)
end
end
raise CustomError.new("an error occurred", {
context_key: "context_value"
})
```
This could also be used to wrap 3rd-party errors with Honeybadger context in a `rescue` statement:
```ruby
begin
rescue 3rdPartyError => e
raise CustomError.new(e.message, {
context_key: e.some_attribute
})
end
```
> Support adding context to exceptions

- lib/honeybadger/plugins/sidekiq.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
It turns out that the retry and retry_count hash entries are not at the top level of the params handed to the error handler but inside the `:job`. As `nil.to_i` always returns 0 the check here never fired.
I've only tried this with the latest Sidekiq Pro but I assume that the standard Sidekiq behaves in the same way. You (as in the company behind Honeybadger) should have an easy time finding out if that is true as all the data is sent to you.
> Fix reporting to Honeybadger after N retries

- lib/honeybadger/conversions.rb
- lib/honeybadger/util/sanitizer.rb
- spec/unit/honeybadger/notice_spec.rb
- spec/unit/honeybadger/util/sanitizer_spec.rb
When preparing data to serialize as JSON for our API, we whitelist a few core types which are supported by JSON: `Hash`, `Array`, `Set`, `Numeric`, `TrueClass`, `FalseClass`, `NilClass`, and `String`. When an object is not one of those types, we convert it to its `String` representation using `#to_s` (and perform some additional sanitization on the result).
This PR adds a new conversion protocol that is used before the final `String` conversion. When the method `#to_honeybadger` is defined on an object, the return value of that method will be used in place of the object itself. The return value can be anything, since it's passed recursively back to the object sanitizer.
If you define `#to_s` on your Rails models, it's probably some human-readable string such as a name or email …
> Add a conversion protocol for serializing unknown objects

- lib/honeybadger/agent.rb
This is a very small tweak to pick up a performance improvement on the
hash manipulation. I noticed this while running Rubocop.
[This is the documentation](http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Performance/RedundantMerge) for the cop which picked this one up.
This is a fairly small change but it's incredibly low risk so I don't see any harm in pulling it in.
> Improve hash merge performance

- lib/honeybadger/plugins/sidekiq.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
Mike estimates that 90% of Sidekiq users are past 3.3.0, which is 3 years old and is the version which introduced the Sidekiq::Middleware::Chain#prepend method.
This PR switches our Sidekiq plugin to use `Chain#prepend` rather than `Chain#add`. The benefit of this is that Honeybadger context can be used inside of additional Sidekiq middleware.
I considered adding a deprecation warning for Sidekiq < 3.3.0, but ideally I'd like to move faster than that, and since this isn't breaking our API (only removing support for an unsupported version of Sidekiq), my plan is to release this in (coincidentally) version 3.3.0 of the honeybadger gem.
/cc @minhajuddin @aselder
Fixes #248
> Use prepend to add Sidekiq Middleware

- CHANGELOG.md
- lib/honeybadger.rb
- lib/honeybadger/init/rails.rb
- lib/honeybadger/init/ruby.rb
- lib/honeybadger/init/sinatra.rb
When a rails app had a dependency on sinatra (imported in gems like resque), the
at_exit callback wasn't being set up at all. This fixes it by explicitly
setting up the at_exit callbacks in rails and ruby init scripts
> Fix at_exit callback being skipped in a rails app with sinatra

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
Rails 5 uses Rack 2 which introduces two new exception classes to indicate poorly formatted parameters.
- Rack::QueryParser::InvalidParameterError
- Rack::QueryParser::ParameterTypeError
Both of these are turned in to 400 Bad Requests automatically by ActionDispatch, yet still get reported to Honeybadger by default. These should be treated like ActionDispatch::ParamsParser::ParseError and ActionController::BadRequest
> Add new Rack exceptions to default ignore list.

- lib/honeybadger/agent.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/ruby.rb
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/config/ruby_spec.rb
- spec/unit/honeybadger/notice_spec.rb
This is a first pass at solving #246.
Based on my discussion with @joshuap, I created a sample implementation of the DSL. The DSL can be used in three ways:
```ruby
thing_that_responds_to_call = ->(notice) { notice.context(from_hook: true) }
Honeybadger.configure do |config|
config.before_notify(thing_that_responds_to_call)
end
Honeybadger.configure do |config|
config.before_notify do |notice|
notice.context(from_hook: true)
end
end
Honeybadger.configure do |config|
hooks = config.before_notify
end
```
I also added a setter for `Notice#api_key` because that will be useful in the "before notify" hooks for routing errors to different projects without having to remember to do that throughout your code base.
Having not written the implementation that I intend to write yet (that's a problem …
> Add "before notify" hooks via Ruby configuration

- lib/honeybadger/config/ruby.rb
This fixes a bug where the logger isn't initialized when logging in `Config::Ruby`. The #logger and #backend methods both do some lazy initialization which wasn't being performed.
> Fix logging bug in before_notify feature

- CHANGELOG.md
- lib/honeybadger/singleton.rb
- spec/features/at_exit_spec.rb
- spec/fixtures/ruby_custom_crash.rb
> Ignore SIGTERM signal exceptions.

- .travis.yml
This was a small fix, so I added it before asking. Should we just update the version of jruby instead of adding a new patch version? Maybe this isn't even necessary. This would increase the build times of our already slow travis jobs.
> Add latest jruby version to the travis test matrix

- CHANGELOG.md
- lib/honeybadger/notice.rb
- lib/honeybadger/util/request_hash.rb
- lib/honeybadger/util/request_payload.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/notice_spec.rb
- spec/unit/honeybadger_spec.rb
This is an alternative implementation of #277 for #271 
The main difference is that it ensures that the the new setters work the same way as the options to `Honeybadger.notify({})`, and it moves the construction and sanitization that was happening to `#as_json`.
The biggest breaking change is that `Honeybadger::Backtrace` (a private class) is no longer exposed directly to the user via `Notice#backtrace`. Now `Notice#backtrace` returns the raw backtrace, which was already what the `:backtrace` option supported and what the new `#backtrace=` setter supports, and the backtrace is parsed in `Notice#as_json`. See CHANGELOG.md for other breaking changes.
Merging this should update master to target a v4.0.0 release of the gem.
> Make notice options assignable

- CHANGELOG.md
- lib/honeybadger/agent.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/ruby.rb
Fixes #272 
I don't seem to find documentation for `Honeybadger.before_notify`, we should update our docs to add this. The PR for this is still open: https://github.com/honeybadger-io/docs/pull/29
> Deprecate Honeybadger.exception_filter

- CHANGELOG.md
When adding the new 4.0 syntax I was receiving a NoMethod error when trying to set `exception_fingerprint` for notice. When I switched to setting `fingerprint` everything seemed to work as intended. I believe this CHANGELOG example needs to be updated with `fingerprint`. The [docs](https://docs.honeybadger.io/ruby/getting-started/customizing-error-grouping.html#customizing-the-grouping-for-all-exceptions) also likely need to be updated.
> Fix CHANGELOG Fingerprint Example

- CHANGELOG.md
- lib/honeybadger/worker.rb
The check for the max queue size is not synchronized, which means it can
return wrong results if multiple threads are pushing on to this queue at
the same time. If the wrong result is returned on the max_queue_size,
the check will be bypassed and the queue will grow unbounded until
memory is exhausted.
Example:
```
jruby-9.1.12.0 :021 > q = Honeybadger::Worker::Queue.new(10); 100.times { Thread.new { q.push("hello") } }; q.size
=> 10 
jruby-9.1.12.0 :022 > q = Honeybadger::Worker::Queue.new(10); 100.times { Thread.new { q.push("hello") } }; q.size
=> 10 
jruby-9.1.12.0 :023 > q = Honeybadger::Worker::Queue.new(10); 100.times { Thread.new { q.push("hello") } }; q.size
=> 99 
jruby-9.1.12.0 :024 > q = Honeybadger::Worker::Queue.new(10); 100.times { Thread.new { q.push("hello") } }; q.size …
```
> Fix memory leak in worker queue

- CHANGELOG.md
- lib/honeybadger/config.rb
- lib/honeybadger/config/ruby.rb
- spec/unit/honeybadger/config/ruby_spec.rb
- spec/unit/honeybadger/config_spec.rb
before_notify hooks are overridden on subsequent Honeybadger.configure calls
Fixes #301
> fix before_notify hooks bug

- lib/honeybadger/worker.rb
Looking through my sidekiq logs, I found this line:
```
WARN: ** [Honeybadger] Error report failed: project is sending too many errors. id=ID code=18.189894035458565 throttle=1.25 interval=429 level=2 pid=6789
```
The order of interval and response code is wrong.
PS: Once I have more time, I can add a test for that.
> Change order of throttle and response code

- CHANGELOG.md
- lib/honeybadger/breadcrumbs/logging.rb
- spec/fixtures/rails/config/application.rb
- spec/unit/honeybadger/breadcrumbs/logging_spec.rb
closes #315 
Calling `to_s` on the message passed to the logger before attempting to strip. I also added some unit specs around the `LogWrapper` class.
> Deal with non-string breadcrumb log inputs

- lib/honeybadger/plugins/breadcrumbs.rb
:wave: We ran into issues with custom active support notifications that don't have a `finished` timestamp.
Based on [the documentation](https://api.rubyonrails.org/classes/ActiveSupport/Notifications.html#method-c-subscribe) `finished` and `started` can be `nil`.
In this PR, I'm setting the duration to `nil` if `finished` or `started` are `nil`.
I'll add a test and update the changelog later this week unless you want to get at it. :)
> [WIP] [breadcrumb] Handle notifications with no finished timestamp

- CHANGELOG.md
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
1. Adds `Notice#causes`, which allows cause data to be mutated in `before_notify` callbacks (for filtering purposes)
2. Adds `Notice#cause=`, which allows the cause to be changed/disabled in `before_notify` callbacks
3. Changes the `:cause` option to `Honeybadger.notify`; passing `cause: nil` will now disable the cause for the current notice.
This also adds a new `Cause` class, which is intended to be used as a duck type (the class itself is private). It contains three attributes that correspond to similar attributes on `Notice`: `error_class`, `error_message`, and `backtrace`. With this API, filtering cause data inside `before_notify` callbacks looks like this:
```ruby
Honeybadger.configure do |config|
config.before_notify do |notice|
notice.error_message = …
```
> Expose cause data to callbacks

- CHANGELOG.md
- lib/honeybadger/agent.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/worker.rb
- spec/unit/honeybadger/worker_spec.rb
[Feedback wanted!]
This attempts to improve throttling. Here's the approach so far:
1. The max queue size has been reduced from 1000 to 100.
2. The exponential backoff multiple has been reduced from 1.25 to 1.05. See an example and the results at the end of this comment. Suggestions/better formulas are welcome.
3. `sleep` is still used to throttle the worker. When shutting down the worker (when `send_data_at_exit` is enabled), check to see if there is a throttle. If there is, log a warning and skip sending data; there's no point in sending data when it will most likely be rejected by the server anyway.
4. If a request is throttled *during* the shutdown, log the same warning and skip the rest of the queue.
5. Don't sleep anywhere else. Outside of throttling, the worker should always run in …
> Throttling improvements (WIP)

- CHANGELOG.md
- lib/honeybadger/breadcrumbs/logging.rb
- spec/unit/honeybadger/breadcrumbs/logging_spec.rb
This fixes #318 where the original message is converted to a string and stored in `message`. When calling super this string version is used.
The logger class itself doesn't care if the message is an object, from the docs it's supported with the note that when the log is written to an output, the message is converted to a string
> +message+ can be any object, but it has to be converted to a String in order to log it.  
Generally, +inspect+ is used if the given object is not a String. A special case is an +Exception+ object, which will be printed in detail, including message, class, and backtrace.  See #msg2str for the implementation if required.
All arguments passed to add are stored in a variable and then when calling super the original arguments are used explicitly.
> Ensure we call super with the original args in breadcrumbs

- .circleci/config.yml
- CHANGELOG.md
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
Added parameter filtering and refactored so we are only sanitizing metadata.
I was concerned that if we started filtering from the root and the user filtered the word 'active' or any keys we use on the root, it would be removed and would cause problems.
> Added parameter filter to Breadcrumb sanitizer

- CHANGELOG.md
- lib/honeybadger/plugins/resque.rb
- spec/unit/honeybadger/plugins/resque_spec.rb
When a developer sets Honeybadger context within the execution of a Resque
job, they expect it to be included in any notices reported from the job,
including when the job fails.
The previous implementation cleared the context in the `around_perform` 
hook, which executes before the `on_failure` hook. This meant that the 
context was always empty for notices from failed jobs.
This moves clearing the context into the failure handler, and into an
`after_perform` hook. If the job succeeds, the context will be cleared by
`after_perform`. If the job fails, the `after_perform` hook will not run, 
so the context will be available when the notice is created in the
`on_failure` hook, which will then clear the context.
> Include context in notices from failed Resque jobs

- CHANGELOG.md
- lib/honeybadger/config.rb
- lib/honeybadger/config/ruby.rb
- lib/honeybadger/plugin.rb
Empty Proc.new, proc and lambda fall back to the block parameter passed to the parent method. This behavior will be deprecated in Ruby 2.7.
We can replace these with explicit block parameters.
> Replace empty Proc.new with explicit block param

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/plugins/faktory.rb
- spec/unit/honeybadger/plugins/faktory_spec.rb
Added Faktory Plugin, with most of the internals contributed from @scottrobertson (thanks!).
I implemented the logic a little different from the sidekiq version. If there is no job passed along, then the error happened somewhere where retries are not applicable (lifecycle or internals) and we always report. The retry logic is similar to sidekiq, but refactored a little for readability.
I found the job params from the structs in the go project (https://github.com/contribsys/faktory/blob/master/client/job.go#L27)
@joshuap I am defaulting to using the `jobtype` as the component (and 'perform' as action, like sidekiq). Is there a reason to make this an option, like in the sidekiq plugin? I was unsure why you would want component to be nil.
> Faktory Plugin

- CHANGELOG.md
- lib/honeybadger/agent.rb
- spec/unit/honeybadger/agent_spec.rb
closes #337 
Duping and reassigning `opt` before mutation.
> Dup #notify opts before mutating

- CHANGELOG.md
- lib/honeybadger/plugins/sidekiq.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
Our Sidekiq plugin relies on `retry_count` in the job parameters to determine if a job should skip. It was taking the `to_i` of the value and essentially using it as an attempts count. This was causing the job to wait 2 extra executions, as the `retry_count` equals 1 on the third execution (see comment in source for explanation).
This refactor calculates the attempts and uses that to determine if we should skip reporting. Now if `sidekiq.attempt_threshold` is set to the value of 2, then on the second execution, it will report (as opposed to the 4th)
This also updates the specs so they describe the `attempts` instead of `retry_count` so you don't have to the math in your head while working through the specs.
> Fix Sidekiq retry count

- CHANGELOG.md
- lib/honeybadger/breadcrumbs/active_support.rb
Rails master (6.1) causes a deprecation warning for `ActiveRecord::Base.connection_config`
> DEPRECATION WARNING: connection_config is deprecated and will be removed from Rails 6.2 (Use connection_db_config instead) (called from block in default_notifications a .../gems/honeybadger-4.6.0/lib/honeybadger/breadcrumbs/active_support.rb:21)
I haven't yet gone back to check when this method was added.
> Fix Rails 6.1 deprecation warning. 

- CHANGELOG.md
- lib/honeybadger/agent.rb
- spec/unit/honeybadger/agent_spec.rb
Previously, when using an agent with `local_context: true` and breadcrumbs enabled, errors result because when the `Breadcrumbs::Collector` was instantiated, the `@config` instance variable hadn't been initialized. This meant the collector was passed `nil` for its config, and when it attempted to access the breadcrumbs setting, a `NoMethodError` was raised.
This change ensures that we always set up our agent config before instantiating the `Breadcrumbs::Collector`.
I don't have any specific questions, but any and all feedback is very welcome. Hopefully this isn't controversial - there are some minor implementation notes in the commit message.
> Pass config to Breadcrumbs::Collector when local_context: true

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
We recently noticed an HTTP parameter parsing error coming through to our honeybadger errors, which we didn't think should be coming through. In the [defaults](https://docs.honeybadger.io/lib/ruby/getting-started/ignoring-errors.html#ignore-by-class), there is a reference to this now [deprecated class](https://github.com/rails/rails/commit/e16c765ac6dcff068ff2e5554d69ff345c003de1). 
To resolve this problem I have renamed the deprecated class with the new [class](https://api.rubyonrails.org/classes/ActionDispatch/Http/Parameters.html). 
I am unsure if this change should have any testing burden. I didn't see a `defaults_spec` to be updated, let me know if I missed anything else.
> Handle Rails depreciation within defaults.rb 

- CHANGELOG.md
- lib/honeybadger/util/sql.rb
- spec/unit/honeybadger/util/sql_spec.rb
resolves #364 
Replace any invalid characters before we attempt to do any `gsub!`ing.
> Deal with invalid UTF-8 byte sequences during SQL obfuscation

- CHANGELOG.md
- lib/honeybadger/util/sql.rb
I noticed that a new Ruby 2.7 deprecation warning popped up after merging a recent PR (#366) - this is my attempt to fix that.
Let me know what else I can do to help!
> Fix Ruby 2.7 deprecation warning in sql.rb

- lib/honeybadger/breadcrumbs/active_support.rb
- spec/fixtures/rails/config/breadcrumbs.rb
Non-UTF-8 encoded strings can break in our exclusion check (as well as the obfuscator, which we fixed earlier). This PR forces encoding before we do our default regex check.
> Encode sql in exclusion check

- CHANGELOG.md
- lib/honeybadger/breadcrumbs/active_support.rb
We had a submitted issue where DB connections were timing out after upgrading. I _think_ this is the result of accessing the `::ActiveRecord::Base.connection` to collect the adapter name. This **should** only affect Rails < 6 users as the active connection is passed in with the instrumentation event for Rails 6.
This brings back the method to pull the adapter from AR connection config, instead of the `adapter_name` from a connection.
> Avoid calling AR::Base.connection

- CHANGELOG.md
- lib/honeybadger/util/lambda.rb
- spec/unit/honeybadger/util/lambda_spec.rb
The Lambda plugin currently enables itself in all environments where the `AWS_EXECUTION_ENV` environment variable is set, regardless of value.
However, this variable is also set in other contexts, e.g. ECS. In those contexts this results in the plugin overwriting the component and action values set in any notice with nil (since no lambda function or handler data is present in the environment).
This commit updates the requirement test to check the `AWS_EXECUTION_ENV` value for the prefix specified in the [AWS Lambda docs](https://docs.aws.amazon.com/lambda/latest/dg/configuration-envvars.html).
> AWS_EXECUTION_ENV – The runtime identifier, prefixed by `AWS_Lambda_`—for example, `AWS_Lambda_java8`.
Since it's not completely clear what the capitalisation is (edit: or rather, I don't trust …
> Don't enable Lambda plugin in non-Lambda execution environments

- .github/workflows/ruby.yml
- Appraisals
- Gemfile
- gemfiles/binding_of_caller.gemfile
- gemfiles/delayed_job.gemfile
- gemfiles/rack.gemfile
- gemfiles/rack_1.gemfile
- gemfiles/rails.gemfile
- gemfiles/rails5.2.gemfile
- gemfiles/rails6.0.gemfile
- gemfiles/resque.gemfile
- gemfiles/sinatra.gemfile
- gemfiles/sinatra_1.gemfile
- gemfiles/standalone.gemfile
- spec/spec_helper.rb
- Programmatically pulls in rails dependencies
- Moves non-necessary gems into development so they dont need to be installed in gh-actions
- Should improve bundle install speed
- Removes `require 'pry'` since it shouldnt be needed in the spec helper (one less thing to install for gh-actions)
> Feat: Decrease time spent bundle installing in GH Actions

- CHANGELOG.md
- lib/honeybadger/util/revision.rb
- spec/fixtures/rails/config/application.rb
- spec/spec_helper.rb
- spec/unit/honeybadger/config_spec.rb
- spec/unit/honeybadger/logging_spec.rb
Pipe stderr from the `git rev-parse HEAD` to the null device (`/dev/null` on *nix, `NUL` on Windows). Also replaced references to /dev/null in the tests with Ruby's [`FIle::NULL`](https://ruby-doc.org/core-2.5.1/File/Constants.html) (available since Ruby 1.9), so tests can work on Windows also.
> Supress git rev-parse error when fetching Git revision

- lib/honeybadger/agent.rb
- lib/honeybadger/backend/base.rb
- lib/honeybadger/singleton.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/backend/base_spec.rb
- spec/unit/honeybadger_spec.rb
> Support deployment tracking in code

- .github/workflows/ruby.yml
- spec/features/deploy_spec.rb
- spec/features/exec_spec.rb
- spec/features/notify_spec.rb
- spec/spec_helper.rb
- spec/support/feature_helpers.rb
- Uses builtin thor capturing instead of spawning full processes.
So this isnt as full sweeping as I would have liked. Ideally I would have liked to rip out Aruba, but life is all about moderation. This will at least cut down on a decent number of `run_command` 's and should show at least a little improvement in speed. Let me know if you have any questions or comments!
I left the `install` and `notify` specs alone as they were quite...thorny...when attempting to refactor them, Aruba appears to do a lot of isolation for us.
> Use thor capture instead of full `run_command` from aruba.

- CHANGELOG.md
- lib/honeybadger/config/defaults.rb
If a user-agent sends an Accept or Content-Type header with a mal-formed mime-type, then Rails raises. this happens in my app a lot as a result of what seems to be security vulnerability scanning, people sending Accept headers like `"../../../../../../../../../../etc/passwd{%00`
Rails is not vulnerable, everything is fine, but it raises. And Honeybadger then catches and reports. (This started in maybe Rails 6.0, before that malformed MIME type didn't raise, it was just ignored). 
Prior to Rals 6.1, the exception class was non-specific so it was hard to ignore/filter. But Rails 6.1 introduces an exception class just for this. Honeybadger should by default ignore it, it fits in with the other Rails stuff Honeybadger ignores by default.
> By default ignore 'ActionDispatch::Http::MimeNegotiation::InvalidType'

- CHANGELOG.md
- lib/honeybadger/plugins/sidekiq.rb
To avoid problems when Sidekiq may change the default JobRetry constant it may be better to replace the fixed number by the Sidekiq::JobRetry constant
> Replace fixed number with Sidekiq constant

- CHANGELOG.md
- lib/honeybadger/agent.rb
- spec/unit/honeybadger/agent_spec.rb
The new `Honeybadger.track_deployment()` takes keyword argument `env`, but the underlying service API expects `environment`.
This ends up in deployments without environment being set.
In order to fix this without breaking the new API, the PR keeps `env` keyword argument, but "translates" it to `environment`.
Unfortunately there is inconsistent documentation:
`environment` https://docs.honeybadger.io/lib/ruby/getting-started/tracking-deployments.html#heroku-deployment-tracking
vs
`env` https://docs.honeybadger.io/lib/ruby/getting-started/tracking-deployments.html#ruby-deployment-tracking
Follow-up to #397
> Properly set environment in deployment tracking

- CHANGELOG.md
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
Also adds support for space-delimited tags; these strings are
equivalent:
- "foo, bar, baz"
- "foo bar baz"
- "foo, bar baz"
Fixes #421
> Allow special characters in tags

- CHANGELOG.md
- lib/honeybadger/plugin.rb
- lib/honeybadger/plugins/lambda.rb
- spec/unit/honeybadger/plugins/lambda_spec.rb
This PR addresses the issues raised on Slack with the AWS Lambda integration. [The docs say](https://docs.honeybadger.io/lib/ruby/integration-guides/aws-lambda-exception-tracking/#capturing-exceptions):
> Our client does not provide an automatic way to handle uncaught lambda exceptions
Well, let's fix that!
```ruby
hb_lambda def my_lambda_handler(event:, context:)
end
```
With the `hb_lambda ` decorator, errors will now be caught automatically. The `aws_request_id` will also be included in the captured context. It's opt-in (you have to decorate your handlers), so fully backwards-compatible.
1. I've included this method twice, on the global object `main`, and on all `Class` objects, since [Lambda handlers can also be class methods](https://docs.aws.amazon.com/lambda/latest/dg/ruby-handler.h …
>  Improved AWS Lambda integration using decorator

- .github/workflows/ruby.yml
Ref: #429 
There's also a bunch of dead code for supporting 2.5 and below that I've removed locally; once we bump the official minimum version to 2.6, I can raise a PR for those too.
> Remove Ruby 2.6 from CI

- lib/honeybadger/plugins/lambda.rb
Small (but key) addition to #423
I noticed that `serverless-offline` [invokes top-level handlers via `Kernel.send(:handler)`](https://github.com/dherault/serverless-offline/blob/dc510b3eec4567aa4d1558b6218cc7a40c297031/src/lambda/handler-runner/ruby-runner/invoke.rb#L77-L83) (as opposed to just `handler` or even `main.handler`). This means it doesn't call our wrapped handler (because it's defined on `main`, not `Kernel`).
This PR fixes that by ensuring the method is also present on `Kernel`, so either way of invoking works.
Turns out that Ruby's top level is more complicated than I thought. It's not just an instance of `Object` called `main`, it's also the `Kernel` module, which is included in every class (including Kernel's own singleton class). So every "global" function is actually a …
> hb_wrap_handler: Support calling on Kernel

- CHANGELOG.md
- lib/honeybadger/util/revision.rb
- spec/unit/honeybadger/util/revision_spec.rb
This came up in a support ticket. I don't know *why* the detected revision was blank, but this should prevent that case in the future.
> Fix a bug where the auto-detected revision is blank instead of nil

- CHANGELOG.md
- lib/honeybadger/util/request_hash.rb
Fixes #435
A bit hidden, but the [Rack docs mention](https://www.rubydoc.info/gems/rack/Rack/Request)
> It is stateless, the environment env passed to the constructor will be directly modified.
This affects other things, like creating invalid sessions when in API mode.
> Fix inadvertent creation of invalid sessions (closes #435)

- CHANGELOG.md
- lib/honeybadger/init/rails.rb
- spec/integration/rails_helper.rb
Closes #383 
Makes use of the Railtie `before_initialize` hook, which has been around [for a while](https://github.com/rails/rails/commit/3afdfc35e8aec7e6379e093dd1278cb3de54f21b).
`before_initialize` runs after Rails' config and application has booted, but before the framework initializers are run ([docs](https://guides.rubyonrails.org/configuring.html#initialization-events)).
Results:
Error is captured in `at_exit` hook. Basic env information is present.
> Initialize Honeybadger before other Rails initializers (closes #383)

- Appraisals
- CHANGELOG.md
- gemfiles/rails.gemfile
- gemfiles/rails5.2.gemfile
- gemfiles/rails6.1.gemfile
- gemfiles/rails7.0.gemfile
- lib/honeybadger/agent.rb
- lib/honeybadger/plugins/rails.rb
- spec/integration/rails/error_subscriber_spec.rb
- spec/unit/honeybadger/agent_spec.rb
More testing of the Rails' error subscriber shows an error might be reported multiple times (for instance, relayed by Rails to our error subscriber, then raised and caught by our Rack middleware). We already handle this, but we don't set the Rack env's `honeybadger.error_id` properly if the error is already reported. This PR fixes that.
> Return existing notice ID if already reported

- CHANGELOG.md
- lib/honeybadger/notice.rb
- spec/unit/honeybadger/notice_spec.rb
> Expose `notice.parsed_backtrace` method

- .github/workflows/ruby.yml
- lib/honeybadger/notice.rb
I noticed there's gem documentation at https://www.rubydoc.info/gems/honeybadger/Honeybadger/Notice, so I added YARD docs for the method. A bit tricky because YARD's syntax for Hash shapes is weak, but I think this should do it. Also relocated the method so it's together with other accessors.
> Document `parsed_backtrace`

- honeybadger.gemspec
See https://guides.rubygems.org/specification-reference/#metadata
and https://rubygems.org/gems/honeybadger
The docs link on rubygems is currently outdated. I figured I'd also add the /for/ruby landing page as the homepage. Does that work, or should the homepage just be the GitHub repo?
> Update gem metadata

- .github/workflows/ruby.yml
- lib/honeybadger/plugins/rails.rb
Fixes #463 
An extra argument was added to the `DebugExceptions` middleware in https://github.com/rails/rails/commit/c066440b92a31bfd5cdd78b4d2677fcf20860437. We should simply pass along all arguments.
> Fix Rails middleware on Rails 7.1

- .github/workflows/ruby.yml
I don't think this really merits a CHANGELOG entry so I didn't add one.
> Update checkout to v3 to resolve Node 12 deprecation warning.

- CHANGELOG.md
- lib/honeybadger/conversions.rb
- spec/unit/honeybadger/notice_spec.rb
When providing an object to the context that comprises other objects that implement `to_honeybadger_context`, serialise them using the using their `to_honeybadger_context` rather than a simple `to_json`
Resolves #487
> Add support for reporting nested context

- CHANGELOG.md
- lib/honeybadger/config/ruby.rb
- spec/unit/honeybadger/config_spec.rb
Config#respond_to_missing? was hardcoded to `true` instead of mirroring the logic of the `method_missing`. Which can potentially cause issues when extending this gem.
Resolves https://github.com/honeybadger-io/honeybadger-ruby/issues/481
> Fix Honeybadger::Config#respond_to?

- CHANGELOG.md
- lib/honeybadger/backend/base.rb
- lib/honeybadger/worker.rb
- spec/unit/honeybadger/worker_spec.rb
Inform the user about the reason for a 413 response from the API.
> Handle 413 responses

- README.md
This removes the SVG badge in the README for the superseded "JRuby" CI workflow, seeing that **JRuby is tested** in the Ruby workflow.
It also updates the badge to link to not only an SVG, but the the Actions tab, to view the Ruby workflow.
(I don't think the CHANGELOG.md needs and update, does it?)
> README: Remove unused badge, fix link

- CHANGELOG.md
- lib/honeybadger/plugins/sidekiq.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
Closes #493
Starting with Sidekiq 7.1.5 the error handler is passed three arguments. The new argument is the Sidekiq config. The `_config` key from the second argument has been removed.
Support for passing two arguments and expecting the `_config` is still supported but will raise a deprication warning and will be removed in Sidekiq 8.
This change adds an optional third argument to the error handler lambda defaulted to `Sidekiq.default_configuration` as per the Sidekiq changelog on how to handle this.
This should make the gem forwards compatible with Sidekiq 8 (excluding any other breaking changes).
Sidekiq PR introducing this change: https://github.com/sidekiq/sidekiq/pull/6051
> Accept three arguments into Sidekiq error handler

- CHANGELOG.md
- lib/honeybadger/agent.rb
- lib/honeybadger/singleton.rb
- spec/unit/honeybadger/agent_spec.rb
Fixes #426, at least as reported. 
I have not looked through docs and code to see if there are more method signatures that should be fixed.
> FIX: Make notify work with proper ruby keyword arguments

- .gitignore
- CHANGELOG.md
- lib/honeybadger/config.rb
- spec/features/test_spec.rb
As discussed in #447 this is the preferred solution: Simply make the init message a DEBUG level message
Fixes #447
> change: change log level of init message to DEBUG

- honeybadger.gemspec
The [setup ruby](https://github.com/ruby/setup-ruby?tab=readme-ov-file#caching-bundle-install-automatically) action comes with a recommended `bundler-cache` option that caches installed gems locally.
The cache folder is in `vendor/bundle` which eventually ends up in the gem and increases the total size of the gem significantly.
This PR makes sure that the folder is excluded from the gem.
Fixes: #514
> fix: ignore vendor/bundle when creating gem

- lib/honeybadger/agent.rb
- lib/honeybadger/backend/base.rb
- lib/honeybadger/backend/debug.rb
- lib/honeybadger/backend/null.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/events_worker.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/backend/base_spec.rb
- spec/unit/honeybadger/backend/debug_spec.rb
- spec/unit/honeybadger/events_worker_spec.rb
~~This currently is missing a queue and calls the backend directly from the agent.~~
~~Should I implement an events_worker within this PR or in the PR that adds the server backend?~~
Another question: Would it make sense to hand in the timestamp from the agent as an actual DateTime so that we could delegate the serialisation to the specific backend? Feels like it could be useful?
> feat: implement simple debug backend endpoint for events

- lib/honeybadger/agent.rb
- spec/unit/honeybadger/agent_spec.rb
This enables both signatures:
```ruby
Honeybadger.event("user_signed_up", user_id: 123)
Honeybadger.event(event_type: "user_signed_up", user_id: 123)
```
> Support Hash as first argument to Honeybadger#event

- .github/workflows/ruby.yml
- lib/honeybadger/agent.rb
- lib/honeybadger/backend/base.rb
- lib/honeybadger/backend/debug.rb
- lib/honeybadger/backend/null.rb
- lib/honeybadger/backend/server.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/events_worker.rb
- lib/honeybadger/singleton.rb
- lib/honeybadger/util/http.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/backend/base_spec.rb
- spec/unit/honeybadger/backend/debug_spec.rb
- spec/unit/honeybadger/backend/server_spec.rb
- spec/unit/honeybadger/events_worker_spec.rb
- spec/unit/honeybadger/util/http_spec.rb
- spec/unit/honeybadger_spec.rb
This is "the simplest thing that could possibly work" without the "could possibly work" part.
I want make sure 2 things with this PR in this state:
- How would we log structured data to a text logger
- Is the `Honeybagder::event` signature sufficient
Next step would be (can be in this PR or separate) to implement `Honeybadger::logger` but since `Honeybadger::logger` currently already points to the internal logger system, this would need some refactoring.
> feat: implements honeybadger.event by synchronous log call

- lib/honeybadger/plugins/active_job.rb
If ActiveJob isn't loaded (by not requiring active_job/railtie in config/application.rb), then this error occur when Honeybadger is loaded:
plugin error name=active_job class=NoMethodError message="undefined method `active_job' for an instance of Rails::Application::Configuration"
This change rescues that error and disables the plugin.
> fix: don't raise an exception when ActiveJob isn't loaded

- lib/honeybadger/plugins/active_job.rb
- spec/integration/rails/async_queue_adapter_spec.rb
And any other ActiveJob adapters that come along :)
Fixes #518
> feat: track exceptions in :solid_queue

- .github/workflows/check-pr-title.yml
Stores the PR title in an environment variable before usage. This should prevent any unwanted remote code execution.
> fix: store pr title before usage

- lib/honeybadger/agent.rb
- lib/honeybadger/context_manager.rb
- spec/unit/honeybadger_spec.rb
Fixes #247, this is my attempt at the local context problem. Please let me know if there are any further tests you'd like me to add to check if this implementation is solid enough to handle all the possible use cases (thread safety?)
> feat: implement local contexts

- lib/honeybadger/agent.rb
- spec/unit/honeybadger/agent_spec.rb
This PR improves on the local contexts feature introduced in #541 by making `Honeybadger.context` return the result of the block instead of the `Agent` instance when local contexts are used.
This allows seamless wrapping of existing application code:
```ruby
class SuperImportantPaymentProcessing
def call
Honeybadger.context({ tags: ['critical', 'payments'] }) do
{ success: true, charge: }
rescue PaymentError => e
Honeybadger.notify(e) # this still gets tagged!
{ success: false }
end
end
end
```
> feat: return block value if block was passed to Honeybadger.context

- lib/honeybadger/agent.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/counter.rb
- lib/honeybadger/gauge.rb
- lib/honeybadger/histogram.rb
- lib/honeybadger/instrumentation.rb
- lib/honeybadger/metric.rb
- lib/honeybadger/notification_subscriber.rb
- lib/honeybadger/plugins/active_job.rb
- lib/honeybadger/plugins/sidekiq.rb
- lib/honeybadger/registry.rb
- lib/honeybadger/registry_execution.rb
- lib/honeybadger/singleton.rb
- lib/honeybadger/timer.rb
- lib/puma/plugin/honeybadger.rb
This adds metrics aggregation. 
`Honeybadger::Registry` - This class stores all tracked metrics registered in the gem. The registry ensures that only one instance of each unique metric is stored at any time. A metric is defined as unique by it's type, name, and set of attributes.
`Honeybadger::RegistryExecution` - This class is injected into the `CollectorWorker` and is run on a configurable interval. When called, it iterates over all registered metrics, compiles payloads for each, and sent as an event. The registry is then flushed.
`Honeybadger::Metric` - A base metric class from which all other metric classes inherit from. These metric classes record data and compute/track values as needed.
Each metric type's data is shaped differently. Below are examples of what that data looks like …
> feat: implement metric registry for aggregation

- lib/honeybadger/init/rails.rb
- lib/honeybadger/rack/user_feedback.rb
- lib/honeybadger/rack/user_informer.rb
Following up on my comment from 7 years ago.
https://github.com/honeybadger-io/honeybadger-ruby/commit/ab2c8cb71253b096d8fa82e71b83d0bf6ad7489e#r22137232
If I've disabled the middlewares I would like to not see them in `rails middleware`
> perf: don't insert middleware at all if they've been disabled

- lib/honeybadger/plugins/active_job.rb
Setting GoodJob's error handler with `config.good_job.on_thread_error=` in an initializer doesn't change `GoodJob.on_thread_error` by the time our plugin gets loaded.
> fix: access GoodJob config via Rails.application.config

- lib/honeybadger/plugins/active_job.rb
> fix: don't blow up if ActiveJob queue_adapter isn't a string or symbol

- lib/honeybadger/cli/install.rb
- lib/honeybadger/cli/main.rb
- spec/features/install_spec.rb
This makes it easy to enable (or disable) Honeybadger Insights when installing in an application.
```bash
bundle exec honeybadger install apikey --insights
```
cc @joshuap
> feat: add --insights flag to install command

- lib/honeybadger/agent.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/ruby.rb
- lib/honeybadger/event.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/event_spec.rb
Similar to the `before_notify` callback, this adds a `before_event` callback to allow for intercepting of an event. Within the callback you can inspect or modify the payload, or `halt!` the event if you do not want it to be sent.
Example:
```ruby
Honeybadger.configure do |config|
config.before_event do |event|
if event.event_type == "process_action.action_controller" && event[:controller] == "Rails::HealthController"
event.halt!
end
end
end
```
`Event#event_type` - Returns the `event_type` parameter.
`Event#ts` - Returns the generated timestamp, or the `:ts` value in the payload if one was present.
`Event#[]` - Allows you to access the event payload data.
1. If you've fixed a bug or added code that should be …
> feat: add before_event hook for intercepting events

- lib/honeybadger/notification_subscriber.rb
There's no point in reporting statements that equal SCHEMA, BEGIN, or COMMIT. :)
> fix: ignore content-less SQL statements

- lib/honeybadger/config.rb
- lib/honeybadger/plugins/rails.rb
Some Rails applications may have Rails::Console defined (possibly through gems). This would inadvertantly disable Insights in production. The issue with this is that this will enable Insights in legitimate consoles, so we'll need to document how to disable it via ENV variables perhaps.
Disable Insights when starting a Rails console:
```
HONEYBADGER_INSIGHTS_ENABLED=false bin/rails console
```
> fix: do not check for rails console

- lib/honeybadger/config/defaults.rb
- lib/honeybadger/events_worker.rb
- spec/unit/honeybadger/events_worker_spec.rb
We've had a few cases of people getting too many warnings in their logs about the queue being full. This PR increases the default queue size, and it also triggers the warning message only when sending a batch of events instead of every time an event is added to the queue.
> fix: buffer more and warn less

- lib/honeybadger/init/rails.rb
Fixes: https://github.com/honeybadger-io/honeybadger-ruby/issues/579
> fix: disable insights when loading rails console

- lib/honeybadger/config/defaults.rb
- lib/honeybadger/worker.rb
Instead of always linking to app.honeybadger.io, the link shown for the just-created notice should point to the new `connection.ui_host` setting, which defaults to app.honeybadger.io.
> feat: add ability to link to a custom domain after creating a notice

- lib/honeybadger/cli/install.rb
- lib/honeybadger/cli/main.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/worker.rb
- spec/features/install_spec.rb
Make it easy to configure the connection hosts when running the install command.
> feat: add --host and --ui_host flags to install command

- lib/honeybadger/backend/test.rb
- lib/honeybadger/cli/test.rb
- lib/honeybadger/worker.rb
This fixes an issue where the cli test would throw an error when Insights has been enabled.
In addition:
* Adds missing methods for the `Backend::Test` class for the sake of completeness.
* Fixes string interpolation for some info messages.
> fix: add event method for cli backend test

- lib/honeybadger/agent.rb
- lib/honeybadger/config.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/event.rb
- lib/honeybadger/notification_subscriber.rb
- lib/honeybadger/plugins/solid_queue.rb
- spec/unit/honeybadger/agent_spec.rb
Fixes: https://github.com/honeybadger-io/honeybadger-ruby/issues/569
This adds some default events to be ignored:
* sql queries: `BEGIN`, `COMMIT`, and anything related to `solid_queue` and `good_job`.
* calls to the default `Rails::HealthController`.
The config `events.ignore` now behaves exactly like `exceptions.ignore` where if you define it in your config file, it will append to the defaults. There is now a `events.ignore_only` where you can override the defaults.
> feat: define default events to ignore, allow for override

- lib/honeybadger/notification_subscriber.rb
In some cases, the payload connection may be nil, which we should handle gracefully.
> fix: safe navigate adapter_name for payload connection

- lib/honeybadger/instrumentation.rb
- lib/honeybadger/instrumentation_helper.rb
This tries to format the example to hold lines together, and using an indent level.
I saw that the first code line wasn't understood by YARD.
The module, I could not get it to render highlighting:
The regular class worked per normal:
> docs: correct spelling, YARD formatting

- lib/honeybadger/plugins/karafka.rb
If a ruby application is using only the `waterdrop` gem, the `Karafka` namespace is available, but the `monitor` method is not. The plugin will only work if the monitoring is available.
> fix: init karafka plugin only if monitor is available

- honeybadger.gemspec
The `logger` used to be shipped with Ruby, as a bundled gem, but Ruby 3.5.0 no longer includes this gem by default.
Explicitly depending  on it avoids a warning being emitted.
> chore: depend on 'logger' explicitly

- lib/honeybadger/config/defaults.rb
- lib/honeybadger/init/rails.rb
This adds a separate configuration for enabling Insights in a console. By default any automatic instrumentation is disabled when you run `bin/rails console`, then you can set a configuration parameter if you need to have it enabled.
Fixes: https://github.com/honeybadger-io/honeybadger-ruby/issues/622
> feat: add a separate configuration for Insights in a console

- gemfiles/hanami.gemfile
- lib/honeybadger/instrumentation.rb
- lib/honeybadger/registry_execution.rb
Raising an error just because a value isn't specified is a little too aggressive. Instead, we can still register the metric and just log the issue. This should prevent unwanted exceptions from bubbling up into the application. We should also not send any metrics if no samples have been collected.
> fix: don't raise errors in instrumentation metrics

- Gemfile
- gemfiles/binding_of_caller.gemfile
- gemfiles/delayed_job.gemfile
- gemfiles/hanami.gemfile
- gemfiles/rack.gemfile
- gemfiles/rack_1.gemfile
- gemfiles/rails.gemfile
- gemfiles/rails6.1.gemfile
- gemfiles/rails7.0.gemfile
- gemfiles/rails7.1.gemfile
- gemfiles/rails7.2.gemfile
- gemfiles/rails8.gemfile
- gemfiles/resque.gemfile
- gemfiles/sidekiq.gemfile
- gemfiles/sidekiq7.gemfile
- gemfiles/sinatra.gemfile
- gemfiles/standalone.gemfile
- spec/integration/sidekiq_spec.rb
A recent change to rspec-its drops support for ruby 3 as well as using `public_send` for calling methods. We use this for testing private methods which is why some tests were failing.
> fix: pin rspec-its gem to 1.3.1

- lib/honeybadger/init/sinatra.rb
While #549 has removed middleware loading for Rails unless configured, it has also removed the code that prevented the middleware from executing in other frameworks unless configured i.e. `return @app.call(env) unless config[:FLAG]`.
A similar change to rails initializer in #549 is now also required for Sinatra (perhaps the same for Hanami?), because currently it loads **and executes** the feedback and user informer middleware even when they are not configured.
> fix: don't run middleware in Sinatra when not configured

- lib/honeybadger/config/defaults.rb
- lib/honeybadger/gauge.rb
- lib/honeybadger/histogram.rb
- lib/honeybadger/instrumentation.rb
- lib/honeybadger/notification_subscriber.rb
- lib/honeybadger/plugins/active_job.rb
- lib/honeybadger/plugins/net_http.rb
- lib/honeybadger/plugins/sidekiq.rb
- spec/unit/honeybadger/gauge_spec.rb
- spec/unit/honeybadger/histogram_spec.rb
- spec/unit/honeybadger/plugins/net_http_spec.rb
- spec/unit/honeybadger/timer_spec.rb
This adds aggregated metrics for the following plugins:
* rails
* net_http
* sidekiq
Similar to the Karafka plugin, there is now more configuration to fine tune the data:
* `rails.insights.events`
* `rails.insights.metrics`
* `sidekiq.insights.events`
* `sidekiq.insights.metrics`
* `net_http.insights.events`
* `net_http.insights.metrics`
> feat: add aggregated metrics for rails and more

- lib/honeybadger/cli/test.rb
In Rails 8, [route drawing is deferred](https://github.com/rails/rails/commit/cdb283566c5d5251e2f7e663e655e57e8e10abbc#diff-84292fcaae327f1a70e7c3b1ebb55b193dea016c1118a8566930bc5cd2a51ba5R157). It seems the easiest fix is to explicitly reload the routes manually.
> fix: cli test for rails 8

- lib/honeybadger/config/defaults.rb
- lib/honeybadger/plugins/sidekiq.rb
- lib/honeybadger/plugins/solid_queue.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
Similar to Karafka's stats event, this adds the collected cluster based stats as a wide event for Sidekiq and SolidQueue. The previous aggregated metrics can be toggled on, while the new events can be toggled off.
```
sidekiq:
insights:
events: false
solid_queue:
insights:
events: false
sidekiq:
insights:
metrics: true
solid_queue:
insights:
metrics: true
```
In addition, the polling interval has been decreased to 5 seconds to allow for up to date readings.
> feat: add event stats for sidekiq and sq

- lib/honeybadger/config.rb
This means that the gem must be able to report data as well requiring the environment to not be a `development_environment`. This should prevent any unexpected Insights related code to run in dev or test environments.
> feat: only allow for insights to be enabled when public

- lib/honeybadger/agent.rb
- lib/honeybadger/init/hanami.rb
- lib/honeybadger/init/rails.rb
- lib/honeybadger/plugins/active_job.rb
- lib/honeybadger/plugins/delayed_job.rb
- lib/honeybadger/plugins/faktory.rb
- lib/honeybadger/plugins/karafka.rb
- lib/honeybadger/plugins/rails.rb
- lib/honeybadger/plugins/resque.rb
- lib/honeybadger/plugins/shoryuken.rb
- lib/honeybadger/plugins/sidekiq.rb
- lib/honeybadger/plugins/sucker_punch.rb
- lib/honeybadger/plugins/thor.rb
This PR makes the `exceptions.enabled` configuration option work a little better by doing the following:
* Skip loading ErrorNotifier and associated middleware
* Skip hooking into Sidekiq, etc. to report exceptions
* Abort sending any notifications when calling `Honeybadger.notify`
> feat: skip middleware, plugins, and exception reporting when exceptions are disabled

- lib/honeybadger/plugins/rails.rb
This will always set the context from Rails when an error is reported even if it is not handled. This will allow applications to use `Rails.error.set_context` instead of `Honeybadger.context` and still see that context in errors in the UI.
It would have been nice if Rails provided an event for when `set_context` is called so that we can hook into that, but this should be ok for now.
Closes: https://github.com/honeybadger-io/honeybadger-ruby/issues/648
> feat: set context during rails error report

- lib/honeybadger/plugins/rails.rb
When an application uses `Rails.error.set_context` to set context, the gem does not see this data until an error is reported. This change uses the `ActiveSupport::ExecutionContext.after_change` callback so that we can always keep track of context changes. This ensures we can report errors with the proper context outside of Rails error report handling.
Closes: https://github.com/honeybadger-io/honeybadger-ruby/issues/648
Specifically, this will also fix the issue with the way we report errors for ActiveJob.
3. Use a pull request title that conforms to [conventional …
> feat: use after_change for context changes

- honeybadger.gemspec
In Ruby 3.4, requiring ostruct without pulling it in as a gem brings up a deprecation warning. Ostruct is used in the cli and sidekiq load check.
```
$ bin/bundle exec honeybadger deploy --environment=production --revision=... --repository=git@github.com:.../....git'
/home/user/.rbenv/versions/3.4.1/lib/ruby/gems/3.4.0/gems/honeybadger-5.26.1/lib/honeybadger/cli/exec.rb:8: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 3.5.0.
You can add ostruct to your Gemfile or gemspec to silence this warning.
```
Added ostruct as a runtime dependency of the gem which should appease the warning.
1. If you've fixed a bug or added code that should be …
> chore: set ostruct as a gem dependency

- lib/honeybadger/backend/test.rb
- lib/honeybadger/notification_subscriber.rb
- spec/integration/rails/notification_subscriber_spec.rb
We noticed some inconsistencies in the timing of some of our Insights events, so I ran some tests and was able to hackily replicate with multiple concurrent requests.
What I believe is happening is the `Honeybadger::NotificationSubscriber` is shared between all threads of the web server, and since we were using an instance variable to set the start time, if `start` is called multiple times without a called `finish`, we override the time. 
This was a bear to test without getting really nasty. I opted to get sorta nasty and stub `Process.clock_gettime` to return an incrementing number only when called during the `start` method. This test is very brittle since it relies on caller stack. For concurrent executions, this would be overridden and the final durations would have duplicates. …
> fix: ensure instrumentation durations are unique during threaded executions

- .github/workflows/ruby.yml
The Ubuntu 20.04 runner image will be fully unsupported by April 1, 2025.
> chore: bump ubuntu runner

- lib/honeybadger/breadcrumbs/active_support.rb
- lib/honeybadger/config/defaults.rb
Apparently "immediate" is sometimes a thing. :)
> fix: ignore transactions with the immediate keyword

- lib/honeybadger/notice.rb
> feat: set action and component from context

- honeybadger.gemspec
RubyGems is truncating the new gem summary in search results. This will look better:
Release-As: 5.27.4
> docs: shorten the gem summary

- lib/honeybadger/agent.rb
- lib/honeybadger/config/defaults.rb
- lib/honeybadger/event.rb
- spec/unit/honeybadger/agent_spec.rb
Give users a configuration option (`insights.sample_rate`) to specify what percentage of events will be sent to the API. The configuration option can be overridden with some event metadata (`{_hb: {sample_rate: 100}}`), which allows the user to specify that an event should always be sent, regardless of the default sampling. That metadata will be removed from the event payload before it is sent to the API. All metrics events will be sent to the API, regardless of the `sample_rate` setting.
> feat: add sampling

- lib/honeybadger/plugins/solid_queue.rb
Also, ensure the database is connected before loading the SolidQueue plugin.
Fixes #694
> fix: avoid database connections during asset precompilation

- lib/honeybadger/config.rb
- lib/honeybadger/config/defaults.rb
This introduces a new configuration option `insights.exclude_rake_tasks`. By default this includes the `assets:precompile` rake task commonly executed in Rails. This can be overridden to include other tasks when needed.
Closes: https://github.com/honeybadger-io/honeybadger-ruby/issues/694
> feat: exclude insights from rake tasks config

- .github/workflows/ruby.yml
- lib/honeybadger/agent.rb
- lib/honeybadger/context_manager.rb
- lib/honeybadger/singleton.rb
- spec/unit/honeybadger/agent_spec.rb
- spec/unit/honeybadger/events_worker_spec.rb
- spec/unit/honeybadger_spec.rb
Data added to event context will be added to all events reported to the API
> feat: add event context

- lib/honeybadger/plugins/faktory.rb
- lib/honeybadger/plugins/sidekiq.rb
- lib/honeybadger/plugins/sucker_punch.rb
- spec/unit/honeybadger/plugins/faktory_spec.rb
- spec/unit/honeybadger/plugins/sidekiq_spec.rb
This PR makes the Plugins use the new keyword argument arity of `Honeybadger.notify(ex, **options_here)`.
The existing tests all passed, but these were using faking the old arity.
Until there's a release,
```ruby
gem "honeybadger", github: "olleolleolle/honeybadger-ruby", branch: "sidekiq-notify", ref: "a6125fd"
```
Changed the faking in tests for Sidekiq, Factory. 
I left Sucker Punch's tests alone (I don't know how Sucker Punch works) - it was lacking coverage of the changed code path, and I left it like that.
I assume it was introduced in #499.
> fix: use kwargs for .notify in plugins

- lib/honeybadger/notification_subscriber.rb
- spec/unit/honeybadger/notification_subscriber_spec.rb
This expands the job data into an array of objects if we see a jobs key in the message payload
> fix: allow jobs in active job subscriber payloads

- lib/honeybadger/context_manager.rb
- spec/unit/honeybadger/agent_spec.rb
The ContextManager uses a Mutex to synchronize context access. When an object passed to Honeybadger.context responds to to_honeybadger_context and, as a side effect, calls back into Honeybadger's ContextManager (e.g., by calling `Honeybadger.event`), the mutex is already held. 
Because Ruby’s standard Mutex is not reentrant, this causes a thread to deadlock when it tries to reacquire the same lock in the same thread.
Switching from Mutex to Monitor fixes this (at the cost of some performance) because Monitor is a recursive mutex, allowing the same thread to acquire the lock multiple times without deadlocking.
> fix: replace context_manager mutex with a monitor

- lib/honeybadger/config/defaults.rb
These cache events probably aren't that interesting, and they can generate a lot of events.
> perf: ignore more events by default

- lib/honeybadger/plugins/warden.rb
If the user instance implements `to_honeybadger_context`, add it to the context.
Closes #728
> feat: add warden user to Honeybadger context
