lib/honeybadger/util/stats.rb
In our system we had an error 'too many open files in system', and it wasn't pushed to the honeybadger server because it was raisen in exceptional tracker. It's possible to catch Errno::ENFILE and prevent from raising an error while sending an exception to the server.
=> Fix issue with Too many open files in system

CHANGELOG.md, lib/honeybadger/plugins/resque.rb, spec/unit/honeybadger/plugins/resque_spec.rb
=> Native resque plugin.

CHANGELOG.md, lib/honeybadger/plugins/delayed_job/plugin.rb
I have created this pull request to add support for resolving the component and action for Rails 4.2 ActiveJobs.
Since this is a small addition to my previous commits, it would be great to add in a 2.1.x release.
Thank you!
=> Resolve component and action for Rails 4.2 ActiveJobs

README.md
I believe the new docs are ready to go. I rebased so there will only be one commit. The only changes I made since @joshuap 's last review area few typo corrections and minor clarifications.
=> Add Configuration Documentation to README

CHANGELOG.md, lib/honeybadger/plugins/passenger.rb, spec/unit/honeybadger/plugins/passenger_spec.rb
=> Require ::PhusionPassenger.on_event to load passenger plugin. #169

CHANGELOG.md, lib/honeybadger/agent/worker.rb, lib/honeybadger/config.rb, lib/honeybadger/config/defaults.rb
re: https://github.com/honeybadger-io/honeybadger-ruby/issues/171
Not sure what config namespace, if any, this was most appropriate to put under.
=> Add max_queue_size configuration option.

.travis.yml, Appraisals, CHANGELOG.md, gemfiles/sinatra_1.gemfile
This adds sinatra 2.0 to the build.
=> Support Sinatra 2

CHANGELOG.md, lib/honeybadger/notice.rb, spec/unit/honeybadger/notice_spec.rb
=> Move fingerprint calculation to end of Notice#initialize

lib/honeybadger/plugins/shoryuken.rb, spec/unit/honeybadger/plugins/shoryuken_spec.rb
See https://github.com/honeybadger-io/honeybadger-ruby/pull/190/files#r100597534
=> Notify errors in Shoryuken batches

lib/honeybadger/backend/null.rb, lib/honeybadger/cli/test.rb, lib/honeybadger/config.rb, lib/honeybadger/worker.rb
=> Log informative messages in dev mode.

CHANGELOG.md, lib/honeybadger.rb, lib/honeybadger/init/sinatra.rb, lib/honeybadger/singleton.rb
=> Move at_exit callback to an appropriate place for sinatra

CHANGELOG.md, lib/honeybadger/agent.rb, lib/honeybadger/backend/base.rb, lib/honeybadger/backend/debug.rb, lib/honeybadger/backend/null.rb, lib/honeybadger/backend/server.rb, lib/honeybadger/backend/test.rb, lib/honeybadger/singleton.rb, lib/honeybadger/util/http.rb, spec/support/helpers.rb, spec/unit/honeybadger/agent_spec.rb, spec/unit/honeybadger/backend/server_spec.rb, spec/unit/honeybadger/util/http_spec.rb
=> Added ability to perform check ins

CHANGELOG.md, lib/honeybadger/cli/test.rb
=> Fix route name conflict in Rails

CHANGELOG.md, lib/honeybadger/agent.rb, lib/honeybadger/notice.rb, spec/unit/honeybadger/agent_spec.rb, spec/unit/honeybadger/notice_spec.rb, spec/unit/honeybadger_spec.rb
=> Halt notice

CHANGELOG.md
=> Add CHANGELOG entry for before_notify

CHANGELOG.md, lib/honeybadger/agent.rb, lib/honeybadger/config.rb, lib/honeybadger/config/defaults.rb, spec/unit/honeybadger/config_spec.rb
=> Remove disabled config option

CHANGELOG.md, lib/honeybadger/plugins/shoryuken.rb
=> Fix sync throttling in shoryuken

CHANGELOG.md, lib/honeybadger/agent.rb, lib/honeybadger/notice.rb, spec/unit/honeybadger/notice_spec.rb
=> Remove accessor method on notice

CHANGELOG.md, lib/honeybadger/agent.rb, lib/honeybadger/config.rb, lib/honeybadger/config/ruby.rb
=> Deprecate singleton callbacks

CHANGELOG.md, spec/unit/honeybadger/backend/base_spec.rb, spec/unit/honeybadger/backend/debug_spec.rb, spec/unit/honeybadger/backend/null_spec.rb, spec/unit/honeybadger/backend/test_spec.rb
=> Add missing Backend::Server#check_in specs

CHANGELOG.md, lib/honeybadger/cli/main.rb, spec/features/deploy_spec.rb, spec/features/exec_spec.rb, spec/features/notify_spec.rb
=> Add flag to skip rails init on cli commands

lib/honeybadger/backtrace.rb, spec/unit/honeybadger/backtrace_spec.rb
=> Infer correct types when parsing backtraces

lib/honeybadger/cli/main.rb
Probably an unfortunate copy-paste.
I did run specs for good measure, but I'm not sure if this warrants an entry in the CHANGELOG, since no feature changed? Let me know, and I would gladly add it.
=> Minor CLI desc fix

CHANGELOG.md, lib/honeybadger/version.rb, spec/unit/honeybadger/worker_spec.rb
A PR for potential discussion around the previous merged PR's.
=> Release 4.5.1

CHANGELOG.md, lib/honeybadger/config/defaults.rb
No more preview mode for you, crumbs.
=> Breadcrumbs on by default

CHANGELOG.md, lib/honeybadger/notice.rb, spec/unit/honeybadger/notice_spec.rb
=> Alias Notice#controller= Notice#component=

.github/workflows/ruby.yml
I noticed a lot of cache misses in the logs for GH-actions. Testing to see if this speeds up the test suite.
=> Fix: cache misses? possible speed improvement

CHANGELOG.md, lib/honeybadger/cli/install.rb
Closes #413 
New default config file:
=> Add more options to default config file

.github/workflows/ruby.yml, CHANGELOG.md, lib/honeybadger/config/yaml.rb, spec/unit/honeybadger/config/yaml_spec.rb
=> Fix a Ruby 3.1 bug that breaks regexp classes in honeybadger.yml

lib/honeybadger/plugins/lambda.rb
=> Fix Lambda plugin: support Ruby <2.5

lib/honeybadger/templates/feedback_form.erb
=> Remove css height on feedback form submit

lib/honeybadger/cli/heroku.rb, tools/isolation.rb, tools/release.rb
=> Replace the deprecated Bundler.clean_env with Bundler.with_unbundled_env

CHANGELOG.md, lib/honeybadger/backend/test.rb, spec/unit/honeybadger/backend/test_spec.rb
=> Fix Honeybadger::Backend::Test.check_in

CHANGELOG.md, lib/honeybadger/plugins/karafka.rb, spec/unit/honeybadger/plugins/karafka_spec.rb
https://karafka.io/docs/Monitoring-and-logging/
=> Add Karafka plugin

lib/honeybadger/events_worker.rb
These events are too chatty for INFO. ;)
=> fix: use debug log level for reporting sent events

lib/honeybadger/util/sanitizer.rb, spec/unit/honeybadger/util/sanitizer_spec.rb
=> fix: handle non-string hash keys when sanitizing

lib/honeybadger/config/defaults.rb, lib/honeybadger/plugins/active_job.rb, spec/integration/rails/active_job_adapter_spec.rb
=> feat: add active_job.attempt_threshold configuration option

lib/honeybadger/plugins/active_job.rb
=> fix: don't duplicate the error handling done by GoodJob

lib/honeybadger/plugins/active_job.rb
=> fix: do GoodJob.on_thread_error check via hash

honeybadger.gemspec, lib/honeybadger/util/sanitizer.rb
=> fix: squash warning about BigDecimal

lib/honeybadger/event.rb
This allows code that updates the payload in a before_event block to look a little nicer. :)
=> fix: add []= delegator

lib/honeybadger/plugins/sidekiq.rb
=> fix: sidekiq leader check only for version > 6.5

lib/honeybadger/notification_subscriber.rb
=> fix: don't send key in cache event payloads

lib/honeybadger/plugins/sidekiq.rb
=> fix: use top level Sidekiq namespace

lib/honeybadger/event.rb
=> fix: sanitize event payload data

lib/honeybadger/instrumentation_helper.rb
https://github.com/honeybadger-io/honeybadger-ruby/pull/604#issuecomment-2297089654
=> docs: correct example syntax

lib/honeybadger/plugins/karafka.rb
Also fixes the error event name and quotes.
=> feat: add karafka processing_lag to event

.github/workflows/ruby.yml, Appraisals, gemfiles/rails8.gemfile
Looks like we are already compatible with Rails 8 beta1!
cc @cnorm35
=> chore: add Rails 8 beta to CI

lib/honeybadger/agent.rb, lib/honeybadger/notice.rb, spec/unit/honeybadger/notice_spec.rb
=> feat: add request_id to notices

spec/unit/honeybadger/agent_spec.rb, spec/unit/honeybadger/config_spec.rb
=> fix: add specs for ignored events

honeybadger.gemspec
This is the copy that gets displayed in our gem listing on RubyGems. I want it to mention everything we do with our "powerfully simple" messaging. 
This is also the copy Chris displays on his performance monitoring tools page, which I'm going to ask him to add us to. :)
https://gorails.com/tool_categories/performance-monitoring/tools
=> docs: update RubyGems copy

lib/honeybadger/cli/install.rb
This may reduce confusion about what this configuration option does.
=> docs: update report_data comment
